config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :movies do
    collection do
      get 'search', to: 'movies#search'
    end
  end
  resources :clients

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :client, optional: true
  attribute :cover_image_url, :string # Agregamos el atributo para la URL de la imagen

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Cliente Ingresado Correctamente" }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Cliente Actualizado Correctamente" }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.movies.update_all(client_id: nil)
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Cliente Eliminado Correctamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :age)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :set_clients, only: [:new, :edit, :create, :destroy, :update]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
    @movies = @movies.paginate(page: params[:page], per_page: 4)
  end
  def search
    @movies = Movie.where("name ILIKE ?", "%#{params[:search]}%").paginate(page: params[:page], per_page: 4)
    render :index
  end


  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Pelicula Creada Correctamente" }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Pelicula Actualizada Correctamente" }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Pelicula Eliminada Correctamente" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_movie
    @movie = Movie.find(params[:id])
  end

  def set_clients
    @clients = Client.all.pluck(:name, :id)
  end

  # Only allow a list of trusted parameters through.
  def movie_params
    params.require(:movie).permit(:name, :client_id, :cover_image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <tr>
    <th scope="row"><%= client.id %></th>
    <td><%= client.name %></td>
    <td><%= client.age %></td>
    <td><%= client.movies.last %></td>
    <td><%= link_to raw('<i class="fa-solid fa-eye text-warning"></i>'), client, title: "Ver Cliente" %></td>
    <td><%= link_to raw('<i class="fa-solid fa-edit text-warning"></i>'), edit_client_path(client), title: "Editar Cliente" %></td>
  </tr>
</div>

app/views/clients/_form.html.erb
<div class="d-flex justify-content-center align-items-center vh-50 mt-5">
  <%= form_with(model: client, class: "card bg-dark col-lg-6 p-3 text-warning") do |form| %>
    <% if client.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(client.errors.count, "error") %> No puedes borrar este cliente:</h2>

        <ul>
          <% client.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row g-3">
      <div class="col-md-6">
        <%= form.label :name, "Nombre", class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="col-md-6">
        <%= form.label :age, "Edad", class: "form-label" %>
        <%= form.number_field :age, class: "form-control" %>
      </div>

      <div class="col-md-12">
        <%= form.submit "Crear Cliente", class: "form-control btn btn-warning fw-bold text-center" %>
      </div>
    </div>
  <% end %>
</div>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Ver Cliente", @client %> |
  <%= link_to "Volver a Clientes", clients_path %>
</div>

app/views/clients/index.html.erb
<div class="container" style="margin-top: 6%;">

  <div id="clients" class="form-control bg-warning bg-gradient bg-opacity-75 shadow-lg p-4" style="font-family: 'Bungee Spice', cursive;">
    <div class="table-responsive scrollbar scrollbar-young-passion" style="max-height: 400px;">
      <table class="table table-dark table-striped rounded table-bordered">
        <thead class="table-dark sticky-top">
          <tr>
            <th scope="col" style="font-family: 'Bungee Spice', cursive;">ID</th>
            <th scope="col" style="font-family: 'Bungee Spice', cursive;">Nombre</th>
            <th scope="col" style="font-family: 'Bungee Spice', cursive;">Edad</th>
            <th scope="col" style="font-family: 'Bungee Spice', cursive;">Pelicula</th>
            <th scope="col" colspan="3" style="font-family: 'Bungee Spice', cursive;">Acciones</th> <!-- Cambio de título para las acciones -->
          </tr>
        </thead>
        <tbody>
          <% @clients.each do |client| %>
            <%= render client %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<div class="justify-content-center text-center mt-5" style="font-family: 'Bungee Spice', cursive;">
  <h1 class="fs-1">Nuevo Cliente</h1>
        <%= render "form", client: @client %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Volver a Clientes", clients_path %>
  <%= button_to "Eliminar Cliente", @client, method: :delete %>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlockBuster</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Bungee+Spice&display=swap" rel="stylesheet">

  <style>
    body, html {
      margin: 0;
      padding: 0;
      background:#000;
    }

    #welcome {
      background-image: url("<%= asset_path('background_image.jpg') %>"); /* Utilizar asset_path para obtener la ruta de la imagen */
      background-size: cover;
      background-position: center;
      height: 89vh;
      width: 99vw;
      display: flex;
      justify-content: center;
      align-items: flex-end;
      position: relative;
    }

    #welcome h1 {
      color: white;
      font-size: 5rem;
      font-family: 'Bungee Spice', cursive;
      text-transform: uppercase;
      text-shadow: 2px 2px 4px #000;
      padding-bottom: 20px;
    }
  </style>
</head>
<body>
  <div id="welcome">
    <h1>¡Bienvenido a BlockBuster!</h1>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlockBuster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<div class="justify-content-center d-flex align-item-center vh-50 mt-5">
  <div class="card bg-dark col-lg-6 text-warning ">
    <div class="card-body text-center">
      <%= form_with(model: movie) do |form| %>
        <% if movie.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(movie.errors.count, "error") %> no puedes guardar esta película:</h2>

            <ul>
              <% movie.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row g-3">
          <div class="col-md-6">
            <%= form.label :name, "Nombre", class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
          </div>

          <div class="col-md-6">
            <%= form.label :client_id, "Cliente", class: "form-label" %>
            <%= form.select :client_id, options_for_select(@clients), class: "form-select" %>
          </div>

          <!-- Nuevo campo para la URL de la imagen -->
          <div class="col-md-12">
            <%= form.label :cover_image_url, "URL de la Carátula", class: "form-label" %>
            <%= form.text_field :cover_image_url, class: "form-control" %>
          </div>

          <div class="col-md-12">
            <button type="submit" class="btn btn-warning fw-bold text-center">Crear Película</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/movies/_movie.html.erb
<div class="col-12 col-sm-6 col-md-4 col-lg-3 py-2">
  <div class="card card-dark">
    <% if movie.cover_image_url.present? %>
      <%= image_tag movie.cover_image_url, class: "card-img-top" %>
    <% else %>
      <%= image_tag 'default_movie_cover.png', width: 200, height: 300, class: "card-img-top" %>
    <% end %>

    <div class="card-footer btn-outline-danger d-flex justify-content-center">
      <%= link_to "Ver Pelicula", movie, class: "btn fw-bold" %>
    </div>
  </div>
</div>

app/views/movies/edit.html.erb
<div class="justify-content-center d-flex">

<h1>Editar Pelicula</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Ver Pelicula", @movie %> |
  <%= link_to "Volver a Peliculas", movies_path %>
</div>
</div>

app/views/movies/index.html.erb
<style>

.glass
{
background: rgba(121, 145, 255, 0.33);
border-radius: 16px;
box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
backdrop-filter: blur(11.9px);
-webkit-backdrop-filter: blur(11.9px);
border: 1px solid rgba(121, 145, 255, 0.4);
  }
  .glass2
{

background: rgba(230, 13, 255, 0.41);
border-radius: 16px;
box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
backdrop-filter: blur(11.9px);
-webkit-backdrop-filter: blur(11.9px);
border: 1px solid rgba(230, 13, 255, 0.4);
  }

  .pagination {
    display: inline-flex;
    justify-self: unset;
  }
  .pagination a {
    color: white;
    float: center;
    padding: 8px 16px;
    text-decoration: none;
  }

  .current {
    background-color: #272727;
    color: white;
    padding: 8px 16px;

  }

  .pagination .disabled {
    pointer-events: none;
    opacity: 0.3;
    padding: 8px 16px;
  }
  .gap {
    display: none;
  }
  img {
    vertical-align: middle;
    width: 100%;
}
.glow-on-hover {

    border: none;
    outline: none;
    color: #fff;
    background: none;
    cursor: pointer;
    position: relative;
    z-index: 0;
    border-radius: 20px;
}

.glow-on-hover:before {
    content: '';
    background: linear-gradient(45deg, #ff0000, #ff7300, #fffb00, #00ff91, #00ffd5, #002bff, #7a00ff, #ff00c8, #ff006f);
    position: absolute;
    top: -2px;
    left:-2px;
    background-size: 400%;
    z-index: -1;
    filter: blur(5px);
    width: calc(100% + 4px);
    height: calc(100% + 4px);
    animation: glowing 20s linear infinite;
    opacity: 0;
    transition: opacity .3s ease-in-out;
    border-radius: 20px;
}

.glow-on-hover:active {
    color: #000
}

.glow-on-hover:active:after {
    background: transparent;
}

.glow-on-hover:hover:before {
    opacity: 1;
}

.glow-on-hover:after {
    z-index: -1;
    content: '';
    position: absolute;
    width: 100%;
    height: 100%;
    background: none;
    left: 0;
    top: 0;
    border-radius: 20px;
}

@keyframes glowing {
    0% { background-position: 0 0; }
    50% { background-position: 400% 0; }
    100% { background-position: 0 0; }
}

.pulse:hover,
.pulse:focus {
  -webkit-animation: pulse 1s;
          animation: pulse 1s;
  box-shadow: 0 0 0 2em rgba(255, 255, 255, 0);
}

@-webkit-keyframes pulse {
  0% {
    box-shadow: 0 0 0 0 var(--hover);
  }
}

@keyframes pulse {
  0% {
    box-shadow: 0 0 0 0 var(--hover);
  }
}

.pulse {
  --color: #ef6eae;
  --hover: #d51869;
}

button {
  color: var(--color);
  transition: 0.25s;
}
button:hover, button:focus {
  border-color: var(--hover);
  color: #fff;
}
</style>

<div class="container" style="margin-top: 5%">

  <div id="movies">
    <div class="row">
      <% @movies.each do |movie| %>
        <%= render partial: 'movie', locals: { movie: movie } %>
      <% end %>
    </div>
  </div>
</div>

<div class="pagination justify-content-center text-center d-flex m-2">
<%= will_paginate @movies,  class: "pagination  shadow bg-gradient", inner_window: 1, outer_window: 0, previous_label: "&laquo;", next_label: "&raquo;", style:"background-color:#454545" %>
</div>

app/views/movies/new.html.erb
<div class="justify-content-center text-center mt-5" style="font-family: 'Bungee Spice', cursive;">
  <h1 class="fs-1">Nueva Película</h1>
  <%= render "form", movie: @movie %>
</div>

app/views/movies/show.html.erb
<div class="justify-content-center d-flex">
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Editar Pelicula", edit_movie_path(@movie) %> |
  <%= link_to "Volver a Peliculas", movies_path %>

  <%= button_to "Eliminar Pelicula", @movie, method: :delete %>
</div>
</div>

app/views/shared/_navbar.html.erb
<style>
  /* Agregamos la fuente Bungee Spice al estilo del Navbar */
  .navbar-brand {
    font-family: 'Bungee Spice', cursive;
  }
</style>

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bungee+Spice&display=swap" rel="stylesheet">

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="z-index: 10000;">
    <div class="container">
      <%= link_to raw('<i class="fa-solid fa-film fa-2x text-warning"></i>'), root_path, class: 'navbar-brand fs-4 me-3' %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-3">
          <li class="nav-item">
            <%= link_to 'Home', root_path, class: 'nav-link active' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="moviesDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Películas
            </a>
            <ul class="dropdown-menu bg-dark" aria-labelledby="moviesDropdown">
              <li><%= link_to 'Nueva Película', new_movie_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Lista de Películas', movies_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="clientsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Clientes
            </a>
            <ul class="dropdown-menu bg-dark" aria-labelledby="clientsDropdown">
              <li><%= link_to 'Nuevo Cliente', new_client_path, class: 'dropdown-item' %></li>
              <li><%= link_to 'Lista de Clientes', clients_path, class: 'dropdown-item' %></li>
            </ul>
          </li>
        </ul>
        <% if controller_name == "movies" %>
          <form class="d-flex" action="<%= search_movies_path %>" method="get">
            <input class="form-control me-2" type="search" name="search" placeholder="Buscar películas" aria-label="Buscar películas">
            <button class="btn btn-outline-success" type="submit">Buscar</button>
          </form>
        <% end %>
      </div>
    </div>
  </nav>